# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from proto.v1 import product_info_pb2 as proto_dot_v1_dot_product__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/v1/order.proto\x12\x0c\x65\x63ommerce.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bproto/v1/product_info.proto\"]\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\x05items\x18\x02 \x03(\x0b\x32\x15.ecommerce.v1.Product\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t2V\n\x0fOrderManagement\x12\x43\n\x0csearchOrders\x12\x1c.google.protobuf.StringValue\x1a\x13.ecommerce.v1.Order0\x01\x42\x39Z7github.com/omihirofumi/grpc-up-and-running/ecommerce_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/omihirofumi/grpc-up-and-running/ecommerce_v1'
  _globals['_ORDER']._serialized_start=99
  _globals['_ORDER']._serialized_end=192
  _globals['_ORDERMANAGEMENT']._serialized_start=194
  _globals['_ORDERMANAGEMENT']._serialized_end=280
# @@protoc_insertion_point(module_scope)
