# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/product_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15v1/product_info.proto\x12\x0c\x65\x63ommerce.v1\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\"\x1a\n\tProductID\x12\r\n\x05value\x18\x01 \x01(\t2\x89\x01\n\x0bProductInfo\x12<\n\naddProduct\x12\x15.ecommerce.v1.Product\x1a\x17.ecommerce.v1.ProductID\x12<\n\ngetProduct\x12\x17.ecommerce.v1.ProductID\x1a\x15.ecommerce.v1.ProductB9Z7github.com/omihirofumi/grpc-up-and-running/ecommerce_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.product_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/omihirofumi/grpc-up-and-running/ecommerce_v1'
  _globals['_PRODUCT']._serialized_start=39
  _globals['_PRODUCT']._serialized_end=110
  _globals['_PRODUCTID']._serialized_start=112
  _globals['_PRODUCTID']._serialized_end=138
  _globals['_PRODUCTINFO']._serialized_start=141
  _globals['_PRODUCTINFO']._serialized_end=278
# @@protoc_insertion_point(module_scope)
